version: '3'

services:
  bot:
    build: .
    image: wiibleyde/fcbot:latest
    container_name: calculator
    restart: always
    ports:
      - 13337:13337
    volumes:
      - ./logs/:/app/logs/
    environment:
      - PORT=13336
