version: '3'

services:
  bot:
    build: .
    image: wiibleyde/chat:latest
    container_name: chat
    restart: always
    ports:
      - 13337:13337
    volumes:
      - ./logs/:/app/logs/
    environment:
      - CHAT_PORT=13336
      - MAX_USERS=100
